name: chatbot
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.0.2
  flutter_facebook_auth: ^3.3.2+2
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  bloc_test: ^8.0.0
  equatable: ^2.0.0
  sign_in_with_apple: ^3.0.0
  hive: 
  hive_flutter: 
  path_provider: 
  flutter_svg: any
  intl: ^0.17.0

  # stream audio data from mic
  sound_stream: ^0.3.0
  # dialog flow
  dialogflow_grpc: ^0.2.2
  # more stream features
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  hive_generator: 
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/jsons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
